require("dotenv").config();
const express=require("express"),helmet=require("helmet"),morgan=require("morgan");
const Database=require("better-sqlite3"),crypto=require("crypto"),path=require("path"),fs=require("fs");
const PDFDocument=require("pdfkit");
const app=express(),PORT=process.env.PORT||3000,BASE_URL=process.env.BASE_URL||`http://localhost:${PORT}`;
app.use(helmet({contentSecurityPolicy:false}));app.use(morgan("tiny"));app.use(express.json({limit:"1mb"}));app.use(express.urlencoded({extended:true}));app.use(express.static(__dirname));
fs.mkdirSync("data",{recursive:true});const db=new Database("data/quickwork.db");db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,referral_code TEXT UNIQUE NOT NULL,credits INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER,expires_at INTEGER);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,product TEXT,amount INTEGER,currency TEXT DEFAULT 'NGN',status TEXT DEFAULT 'pending',reference TEXT UNIQUE,input_text TEXT,output_text TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS referrals(id INTEGER PRIMARY KEY AUTOINCREMENT,referrer_id INTEGER,referred_id INTEGER,rewarded INTEGER DEFAULT 0);`);
const products=[["cv","Professional CV",5000,"ATS-friendly CV tailored to your career."],["cover-letter","Cover Letter",3500,"A polished cover letter for job applications."],["business-proposal","Business Proposal",7500,"A professional proposal for clients or partners."],["social-pack","Social Media Content Pack",6000,"30 ready-to-edit content ideas and captions."],["business-ideas","Business Idea Pack",4000,"Practical business ideas with launch plans."]].map(([id,name,price,description])=>({id,name,price,description}));
const hash=p=>crypto.createHash("sha256").update(p+(process.env.SESSION_SECRET||"dev")).digest("hex");
const token=()=>crypto.randomBytes(32).toString("hex"),ref=()=> "QW"+crypto.randomBytes(4).toString("hex").toUpperCase();
function user(req){const t=req.headers.authorization?.replace(/^Bearer\s+/i,"");return t?db.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?").get(t,Date.now()):null}
function auth(req,res,next){req.user=user(req);if(!req.user)return res.status(401).json({error:"Login required"});next()}
app.get("/api/products",(q,s)=>s.json(products));
app.post("/api/register",(q,s)=>{let{name,email,password,referralCode}=q.body;if(!name||!email||!password||password.length<6)return s.status(400).json({error:"Enter name, valid email and password of 6+ characters."});try{let c=ref();let i=db.prepare("INSERT INTO users(name,email,password_hash,referral_code) VALUES(?,?,?,?)").run(name.trim(),email.trim().toLowerCase(),hash(password),c);if(referralCode){let r=db.prepare("SELECT id FROM users WHERE referral_code=?").get(referralCode.trim().toUpperCase());if(r&&r.id!==i.lastInsertRowid){db.prepare("INSERT INTO referrals(referrer_id,referred_id) VALUES(?,?)").run(r.id,i.lastInsertRowid);db.prepare("UPDATE users SET credits=credits+500 WHERE id=?").run(r.id)}}s.json({ok:true})}catch(e){s.status(400).json({error:"Email already registered."})}});
app.post("/api/login",(q,s)=>{let{email,password}=q.body,u=db.prepare("SELECT * FROM users WHERE email=? AND password_hash=?").get(String(email||"").toLowerCase(),hash(password||""));if(!u)return s.status(401).json({error:"Invalid email or password"});let t=token();db.prepare("INSERT INTO sessions VALUES(?,?,?)").run(t,u.id,Date.now()+604800000);s.json({token:t,user:{id:u.id,name:u.name,email:u.email,referral_code:u.referral_code,credits:u.credits}})});
app.get("/api/me",auth,(q,s)=>s.json({user:{id:q.user.id,name:q.user.name,email:q.user.email,referral_code:q.user.referral_code,credits:q.user.credits},orders:db.prepare("SELECT id,product,amount,status,reference,created_at FROM orders WHERE user_id=? ORDER BY id DESC").all(q.user.id)}));
app.post("/api/paystack/initialize",auth,async(q,s)=>{let p=products.find(x=>x.id===q.body.productId);if(!p)return s.status(400).json({error:"Product not found"});if(!process.env.PAYSTACK_SECRET_KEY)return s.status(503).json({error:"Paystack is not configured yet"});let r="QW_"+Date.now()+"_"+crypto.randomBytes(3).toString("hex");db.prepare("INSERT INTO orders(user_id,product,amount,status,reference,input_text) VALUES(?,?,?,?,?,?)").run(q.user.id,p.id,p.price,"pending",r,q.body.inputText||"");try{let x=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({email:q.user.email,amount:p.price*100,reference:r,callback_url:`${BASE_URL}/success.html`,metadata:{order_ref:r,user_id:q.user.id,product:p.id}})});let d=await x.json();if(!d.status)throw Error();s.json({authorization_url:d.data.authorization_url,reference:r})}catch(e){db.prepare("UPDATE orders SET status='failed' WHERE reference=?").run(r);s.status(502).json({error:"Could not initialize payment"})}});
function content(o){return `QUICKWORK AI\n\n${o.product.toUpperCase()}\n\n${o.input_text||"Professional document prepared for the customer."}\n\nReview and personalize all names, dates, figures and contact details before use.`}
app.post("/api/paystack/webhook",(q,s)=>{let sig=q.headers["x-paystack-signature"];if(!sig||!process.env.PAYSTACK_SECRET_KEY)return s.status(401).send("invalid");let h=crypto.createHmac("sha512",process.env.PAYSTACK_SECRET_KEY).update(JSON.stringify(q.body)).digest("hex");if(!crypto.timingSafeEqual(Buffer.from(h),Buffer.from(sig)))return s.status(401).send("invalid");if(q.body.event==="charge.success"){let r=q.body.data?.reference,o=db.prepare("SELECT * FROM orders WHERE reference=?").get(r);if(o&&o.status!=="paid"){db.prepare("UPDATE orders SET status='paid',output_text=? WHERE reference=?").run(content(o),r);let x=db.prepare("SELECT * FROM referrals WHERE referred_id=? AND rewarded=0").get(o.user_id);if(x){db.prepare("UPDATE users SET credits=credits+1000 WHERE id=?").run(x.referrer_id);db.prepare("UPDATE referrals SET rewarded=1 WHERE id=?").run(x.id)}}}s.send("ok")});
app.get("/api/orders/:id/pdf",auth,(q,s)=>{let o=db.prepare("SELECT * FROM orders WHERE id=? AND user_id=?").get(q.params.id,q.user.id);if(!o||o.status!=="paid")return s.status(404).send("Document unavailable");s.setHeader("Content-Type","application/pdf");s.setHeader("Content-Disposition",`attachment; filename="quickwork-${o.id}.pdf"`);let d=new PDFDocument({margin:50});d.pipe(s);d.fontSize(20).text("QuickWork AI").moveDown().fontSize(16).text(o.product.toUpperCase()).moveDown().fontSize(11).text(o.output_text||content(o),{lineGap:5});d.end()});
app.get("/api/orders/:id/docx",auth,(q,s)=>{let o=db.prepare("SELECT * FROM orders WHERE id=? AND user_id=?").get(q.params.id,q.user.id);if(!o||o.status!=="paid")return s.status(404).send("Document unavailable");s.setHeader("Content-Type","text/plain");s.setHeader("Content-Disposition",`attachment; filename="quickwork-${o.id}.txt"`);s.send(o.output_text||content(o))});
app.get("/api/admin/stats",(q,s)=>{if(q.headers["x-admin-key"]!==process.env.ADMIN_KEY)return s.status(401).json({error:"Unauthorized"});s.json({users:db.prepare("SELECT COUNT(*) c FROM users").get().c,orders:db.prepare("SELECT COUNT(*) c FROM orders").get().c,paid:db.prepare("SELECT COUNT(*) c FROM orders WHERE status='paid'").get().c,revenue:db.prepare("SELECT COALESCE(SUM(amount),0) n FROM orders WHERE status='paid'").get().n,recent:db.prepare("SELECT id,product,amount,status,created_at FROM orders ORDER BY id DESC LIMIT 50").all()})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"index.html")));
